/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { PlonkVerifier, PlonkVerifierInterface } from "../PlonkVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610220806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80639649daae14610030575b600080fd5b61004a60048036038101906100459190610133565b610060565b60405161005791906101cf565b60405180910390f35b600060019050949350505050565b600080fd5b600080fd5b600080fd5b600080fd5b600080fd5b60008083601f84011261009d5761009c610078565b5b8235905067ffffffffffffffff8111156100ba576100b961007d565b5b6020830191508360018202830111156100d6576100d5610082565b5b9250929050565b60008083601f8401126100f3576100f2610078565b5b8235905067ffffffffffffffff8111156101105761010f61007d565b5b60208301915083602082028301111561012c5761012b610082565b5b9250929050565b6000806000806040858703121561014d5761014c61006e565b5b600085013567ffffffffffffffff81111561016b5761016a610073565b5b61017787828801610087565b9450945050602085013567ffffffffffffffff81111561019a57610199610073565b5b6101a6878288016100dd565b925092505092959194509250565b60008115159050919050565b6101c9816101b4565b82525050565b60006020820190506101e460008301846101c0565b9291505056fea264697066735822122018f9bc10c26c935b9c411b7a41b805d403e1f39cc93f25dbb975cee151714abb64736f6c63430008110033";

type PlonkVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PlonkVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PlonkVerifier__factory extends ContractFactory {
  constructor(...args: PlonkVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PlonkVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PlonkVerifier__factory {
    return super.connect(runner) as PlonkVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PlonkVerifierInterface {
    return new Interface(_abi) as PlonkVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PlonkVerifier {
    return new Contract(address, _abi, runner) as unknown as PlonkVerifier;
  }
}
